apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sendmail
  namespace: dapr-trafficcontrol
spec:
  type: bindings.smtp
  version: v1
  metadata:
  - name: host
    value: mailserver
  - name: port
    value: 25
  - name: user
    secretKeyRef:
      name: trafficcontrol-secrets
      key: smtp.user
  - name: password
    secretKeyRef:
      name: trafficcontrol-secrets
      key: smtp.password
  - name: skipTLSVerify
    value: true
scopes:
  - finecollectionservice
