apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dapr-trafficcontrol
spec:
  type: state.redis
  version: v1
  metadata:
  - name: "redisHost"
    value: "redis:6379"
  - name: actorStateStore
    value: "true"
scopes:
  - trafficcontrolservice