apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dapr-trafficcontrol
spec:
  type: state.redis
  version: v1  
  metadata:
  - name: "redisHost"
    value: "redis-master.dapr-trafficcontrol.svc.cluster.local:6379"
  - name: "redisPassword"
    secretKeyRef:
      name: redis
      key: redis-password