apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicleregistrationservice
  namespace: dapr-trafficcontrol
  labels:
    app: vehicleregistrationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicleregistrationservice
  template:
    metadata:
      labels:
        app: vehicleregistrationservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "vehicleregistrationservice"
        dapr.io/app-port: "6002"
        dapr.io/config: "dapr-config"
    spec:
      containers:
      - name: vehicleregistrationservice
        image: dapr-trafficcontrol/vehicleregistrationservice:1.0
        ports:
        - containerPort: 6002

